######################################################################
# Automatically generated by qmake (3.0) Tue Feb 17 02:19:23 2015
######################################################################

include(../src/qinotifyfswatcher.pri)

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += main.cpp
