######################################################################
# Automatically generated by qmake (3.0) Tue Feb 17 02:20:29 2015
######################################################################

INCLUDEPATH += $$PWD

# Input
HEADERS += $$PWD/qinotifyfswatcher.h
SOURCES += $$PWD/qinotifyfswatcher.cpp

CONFIG += c++11
